// Auto-generated file. Do not edit manually.
// Generated on 2025-10-31T04:54:40.905Z
// Source: home.png

export const HOME_IMAGE = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANAAAADQCAMAAABBeh9GAAAAV1BMVEUAAABgYGBdXV1cXFxgYGBbW1tcXFxbW1taWlpcXFxbW1teXl5cXFxYWFhcXFxcXFxbW1taWlpdXV1dXV1bW1tcXFxcXFxbW1tcXFxcXFxcXFxcXFxcXFwNFWMYAAAAHXRSTlMAEGBvIN//3mD+cE/vIK+/nzDf3p5Avs7tgFB/bjxoHtwAAAGrSURBVHgB7c9TYiRgGADBP7adzP2vuTbGU4t0v3+oURuuqqqqqqqqqqqqqqqqqqq2tnd2hwq0u7e/vydFwINFwONEwPOpAykCHiwCHiwCHiwCHiwCHiwCHiwCHiICHiACHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHioCHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiCiHiGSHiNyHiVSHicyHikSHisCHiwCHiwCHiwCHiwCHiwCHiwCHiwCHiwCHiwCHivaWiPocP/Pd7S9RtDx3wA6WSNo6/TPgw7Oxho7O7/4LgG8+K7Lq7HJrjfvuRlrKVCgQIECBQoUKFCgi9sZXfxjoO0xo+1AgQIFCuQKFChQoECBAgUKFChQoECBAgUKFChQoECBAgUKFChQoECBAgVSXezP6G7M6G5/RvcUdHd0tD+lo4cxs/vpGx7vBu1s52lKz2OOnqcseJmcjaqqqqqqqqqqqqqqqqqqqgV7CwLr8wvhgL7zAAAAAElFTkSuQmCC";
